Add cleanup step

diff --git a/.github/workflows/rocm-release-jax.yml b/.github/workflows/rocm-release-jax.yml
--- a/.github/workflows/rocm-release-jax.yml
+++ b/.github/workflows/rocm-release-jax.yml
@@ -36,8 +36,17 @@ jobs:
     runs-on: mi-250
     env:
       RELEASE_DOCKER_IMG_NAME: "rocm/jax-build:rocm${{ inputs.rocm_version}}-jax${{ inputs.jax_version }}-py${{ inputs.python_version }}-${{ github.sha }}"
-      WORKSPACE_DIR: workdir_${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}
+      WORKSPACE_DIR: workdir_release_${{ github.run_id }}_${{ github.run_number }}_${{ github.run_attempt }}
     steps:
+      - name: Clean up Docker and old run directories
+        run: |
+          # Remove old docker images
+          docker image rm rocm/jax-build:rocm*
+          # Make sure we own all the files that we clean up
+          docker run -v "./:/jax" ubuntu /bin/bash -c "chown -R $UID /jax/workdir_release_* || true"
+          # Remove old work directories from this machine
+          rm -rf workdir_release_*
+          ls
       - name: Print system info
         run: |
           echo RELEASE_DOCKER_IMAGE_NAME=$RELEASE_DOCKER_IMAGE_NAME
@@ -45,10 +54,6 @@ jobs:
           whoami
           df -h
           rocm-smi
-      - name: Clean up Docker and old runs
-        run: |
-          # Remove old directories and docker images
-          echo "Not implemented yet"
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
         with:
           path: ${{ env.WORKSPACE_DIR }}
@@ -58,12 +63,12 @@ jobs:
           # Let ci_build script do the build
           python3 ./build/rocm/ci_build \
             --compiler clang \
-            --python-versions ${{ inputs.python_version }} \
-            --rocm-version ${{ inputs.rocm_version }} \
-            --rocm-build-job ${{ inputs.rocm_build_job_name }} \
-            --rocm-build-num ${{ inputs.rocm_build_job_num }} \
+            --python-versions 3.10.12 \ # ${{ inputs.python_version }} \
+            --rocm-version 6.3.3 \ # ${{ inputs.rocm_version }} \
+            --rocm-build-job 1 \ ${{ inputs.rocm_build_job_name }} \
+            --rocm-build-num 2 \ ${{ inputs.rocm_build_job_num }} \
             dist_docker \
-            --image-tag $RELEASE_DOCKER_IMG_NAME
+            --image-tag $RELEASE_DOCKER_IMG_NAME \
       - name: Archive wheels to Github
         uses: actions/upload-artifact@v4
         with:
